### ISSUE TITLE
qsort_op.lua question

### ISSUE THREAD

**Issue by achan001** [DarkRoku12/lua_sort#2]
on line 85 : if j < i then break end
should it be if j <= i then break end ?

also, does removing function set2 speed up the code ?

i am using old luajit 1.1.8, and i get 10% speed up with -O vs table.sort
great job !

**Comment by DarkRoku12** [comment]
May be, but it is a port, so i tried to make 1 to 1 correspondence with the C source code.

So this is part of the source code:
https://github.com/DarkRoku12/lua_sort/blob/97c376c727eeeffc5279a94adf088cb59aaddf48/lib_table_sort.c#L81-L101

And this is the corresponding part on the Lua version
https://github.com/DarkRoku12/lua_sort/blob/97c376c727eeeffc5279a94adf088cb59aaddf48/qsort_op.lua#L63-L90

So: (Lua)
https://github.com/DarkRoku12/lua_sort/blob/97c376c727eeeffc5279a94adf088cb59aaddf48/qsort_op.lua#L85-L87

correspond to: (C)
https://github.com/DarkRoku12/lua_sort/blob/97c376c727eeeffc5279a94adf088cb59aaddf48/lib_table_sort.c#L95-L99

> also, does removing function set2 speed up the code ?

I don´t think so, at least not in LuaJIT 2+, you can read on this link (it is a bit hidden though)
http://luajit.org/ext_profiler.html
> The results for JIT-compiled code may sometimes be surprising. LuaJIT heavily **optimizes and inlines** Lua code — there's no simple one-to-one correspondence between source code lines and the sampled machine code.

**Comment by achan001** [comment]
I thought your raw version was the direct port.

FYI, on luajit 1.1.8, removing set2 and use repeat until construct
speed up another 10% (i.e 20 % vs table.sort)

is there any difference between lua version vs c version ?
is it safe to put this on my init.lua ?

table.sort = require 'qsort_op'      -- remove c version altogether

**Comment by DarkRoku12** [comment]
Yes, i think is function is already safe to use, i don´t think it will yield different results than the C version.
And i think that you can use an intermediate check function, if the JIT compiler is enabled, use the Lua pure version, otherwise, use the original C version.

**Comment by achan001** [comment]
just an update to table.sort :

recompile luajit without c table.sort ... smaller lua51.dll
update init.lua with table.sort = require 'qsort_op'

changed the test j < i to j <= i for more efficient code
removed set2 function, local variable P2, b
use repeat until construct ... 20% speedup
(tried set P=nil after done with pivot, but code run slower ... jit compiler is unpreditable)

exposed the index for sorting, so now i can do this:

table.sort(t, nil, 0)          -- 0 based table
table.sort(t, nil, 10, 16)  -- only need partial inplace sort
